stages:
  - test
  - publish

test:
  stage: test
  image: openjdk:8
  tags:
    - docker-builder
  script:
    - ./gradlew -Dorg.gradle.daemon=false clean test

publish:
  stage: publish
  image: openjdk:8
  tags:
    - docker-builder
  variables:
    PUBLISH_AUTH: ${NEXUS_AUTH}
    PUBLISH_URL: ${NEXUS_URL_RELEASE}
  script:
    - ./gradlew -Dorg.gradle.daemon=false clean publish
    - ./gradlew -Dorg.gradle.daemon=false publishPlugins -Pgradle.publish.key=${GRADLE_PUBLISH_KEY} -Pgradle.publish.secret=${GRADLE_PUBLISH_SECRET}
  only:
    - tags
    
    